[package]
name = "oyasumi"
version = "0.1.1"
description = ""
authors = ["Raphiiko"]
license = "MIT"
repository = ""
default-run = "oyasumi"
edition = "2021"
rust-version = "1.63.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.5", features = ["dialog-open", "fs-read-file", "shell-execute", "shell-open", "updater"] }
lazy_static = "1.4.0"
cronjob = "0.4.17"

[dependencies.tauri-plugin-store]
git = "https://github.com/tauri-apps/tauri-plugin-store"
branch = "dev"

[dependencies.openvr]
git = "https://github.com/rust-openvr/rust-openvr"
rev = "449cb77c1e07a36dd437a364048c1f3f52330f09"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
