[package]
name = "oyasumi-elevated-sidecar"
version = "1.2.1"
authors = ["Raphiiko"]
license = "MIT"
edition = "2021"
rust-version = "1.64.0"

[dependencies]
oyasumi-shared = { path = "../src-shared", version = '*' }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
nvml-wrapper = "0.8.0"
lazy_static = "1.4.0"
reqwest = "0.11.12"
sysinfo = "0.26.2"

[dependencies.tokio]
version = "1.21.1"
features = ["full"]

[dependencies.hyper]
version = "0.14.20"
features = ["full"]

[dependencies.windows-sys]
version = "0.36.1"
features = ["Win32_UI_Shell", "Win32_Foundation"]

[dependencies.winapi]
version = "0.3.9"
features = ["handleapi", "processthreadsapi", "winnt", "securitybaseapi", "impl-default"]

