[package]
name = "oyasumi-shared"
version = "0.0.0"
authors = ["Raphiiko"]
edition = "2021"
license = "MIT"
rust-version = "1.63.0"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dependencies.openvr]
git = "https://github.com/rust-openvr/rust-openvr"
rev = "449cb77c1e07a36dd437a364048c1f3f52330f09"