name: 'Release Build'
on:
  push:
    branches:
      - master
      - main

jobs:
  build-release:
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-latest ]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Get Package Version
        id: get-package-version
        uses: stevenbenitez/get-package-version-action@v1
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install NodeJS dependencies
        run: yarn
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src-shared
            src-elevated-sidecar
            src-tauri
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          version: ${{ steps.get-package-version.outputs.version }}
          path: ./CHANGELOG.md
      - name: Build and release Oyasumi
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: oyasumi-v${{ steps.get-package-version.outputs.version }}
          releaseName: Oyasumi v${{ steps.get-package-version.outputs.version }}
          releaseBody: ${{ steps.changelog_reader.outputs.changes }}
          releaseDraft: false
          includeUpdaterJson: true
      - name: Update the update manifest
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GH_TOKEN_GIST }}
          gist_id: 16ed38d8ccd9282675d04478f887f76f
          file_path: latest.json
          gist_file_name: 'oyasumi_update_manifest.json'
          gist_description: Oyasumi Update Manifest [Release Channel]
