name: 'Development Check & Build'
on:
  push:
    branches:
      - develop

jobs:
  build-dev-release:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install NodeJS dependencies
        run: npm install
      - name: Set app version to DEV version
        run: npm run set-version DEV
      - name: Lint Angular project
        run: npm run lint
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src-shared
            src-elevated-sidecar
            src-tauri
      - name: Check Rust code in shared module
        run: cd src-shared && cargo clippy --all-features --no-deps
      - name: Check Rust code in elevated sidecar module
        run: cd src-elevated-sidecar && cargo clippy --all-features --no-deps
      - name: Check Rust code in core module
        run: >
          mkdir -p dist/oyasumi/ # Create empty dist folder
          mkdir -p src-elevated-sidecar/target/release/ # Create empty target folder for sidecar executable
          touch src-elevated-sidecar/target/release/oyasumi-elevated-sidecar.exe  # Create dummy sidecar executable
          node scripts/move-sidecar-build.js # Rename dummy sidecar executable to the correct name
          cd src-tauri
          cargo clippy --all-features --no-deps # Check Rust code in core module
          rm src-elevated-sidecar/target/release/oyasumi-elevated-sidecar*.exe # Clean up dummy sidecar executable(s)
      - name: Delete new development release and tag if they exist
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        continue-on-error: true
        with:
          delete_release: true
          tag_name: oyasumi-vDEV-new
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          version: Unreleased
          path: ./CHANGELOG.md
      - name: Build and release Oyasumi development build
        uses: Raphiiko/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: oyasumi-vDEV-new
          releaseName: Oyasumi Development Build
          releaseBody: ${{ steps.changelog_reader.outputs.changes }}
          releaseDraft: false
          prerelease: true
          includeDebug: true
          includeRelease: false
      - name: Get current development release ID if it exists
        uses: actions/github-script@v6
        continue-on-error: true
        id: get-current-release-id
        with:
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: "oyasumi-vDEV"
            })
            return release.data.id
      - name: Get new development release ID
        uses: actions/github-script@v6
        id: get-new-release-id
        with:
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: "oyasumi-vDEV-new"
            })
            return release.data.id
      - name: Delete current development release and tag if they exist
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        continue-on-error: true
        with:
          delete_release: true # default: false
          tag_name: oyasumi-vDEV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create development tag on current commit
        uses: EndBug/latest-tag@latest
        with:
          ref: oyasumi-vDEV
      - name: Set new tag on new development release
        uses: actions/github-script@v6
        env:
          release_id: ${{ steps.get-new-release-id.outputs.result }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              tag_name: "oyasumi-vDEV"
            })
      - name: Delete temporary development tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: oyasumi-vDEV-new
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
