name: 'Steam Release Build'
on:
  push:
    branches:
      - develop
      - master
      - main

jobs:
  build-steam-release:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-latest ]
    runs-on: ${{ matrix.platform }}
    outputs:
      appVersion: ${{ steps.get-package-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Get Package Version
        id: get-package-version
        uses: stevenbenitez/get-package-version-action@v1
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Initialize the project
        run: npm run ci
      - name: Set flavour to STEAM
        run: npm run set-flavour STEAM
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src-shared-rust
            src-elevated-sidecar
            src-core
      - name: Install development Tauri CLI
        run: cargo install --git https://github.com/tauri-apps/tauri --branch 1.x tauri-cli
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          version: ${{ steps.get-package-version.outputs.version }}
          path: ./CHANGELOG.md
      - name: Build OyasumiVR
        run: cargo-tauri build -b none
      - name: Move artifacts
        shell: bash
        run: |
          mkdir -p build/Win64
          mv src-core/target/release/OyasumiVR.exe build/Win64/
          mv src-core/target/release/openvr_api.dll build/Win64/
          mv src-core/target/release/resources/ build/Win64/
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deploy-to-steam:
    runs-on: ubuntu-latest
    needs: build-steam-release
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: build
      - uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_BUILD_USER }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}
          appId: 2538150
          buildDescription: v${{ needs.build-steam-release.outputs.appVersion }}
          rootPath: build
          depot1Path: Win64
          releaseBranch: prerelease

