name: 'Development Build'
on:
  push:
    branches:
      - develop

jobs:
  build-dev-release:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-latest ]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install NodeJS dependencies
        run: npm install
      - name: Set app version to DEV version
        run: npm run set-version DEV
      - name: Lint Angular project
        run: npm run lint
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src-shared
            src-elevated-sidecar
            src-tauri
      - name: Check Rust code in shared module
        run: cd src-shared && cargo clippy --all-features --no-deps
      - name: Check Rust code in elevated sidecar module
        run: cd src-elevated-sidecar && cargo clippy --all-features --no-deps
      - name: Check Rust code in core module
        run: |
          mkdir -p dist/oyasumi/ # Create empty dist folder
          mkdir -p src-elevated-sidecar/target/release/ # Create empty target folder for sidecar executable
          touch src-elevated-sidecar/target/release/oyasumi-elevated-sidecar.exe  # Create dummy sidecar executable
          node scripts/move-sidecar-build.js # Rename dummy sidecar executable to the correct name
          cd src-tauri
          cargo clippy --all-features --no-deps # Check Rust code in core module
          rm src-elevated-sidecar/target/release/oyasumi-elevated-sidecar*.exe # Clean up dummy sidecar executable(s)
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          version: Unreleased
          path: ./CHANGELOG.md
      - name: Build and release Oyasumi development build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          releaseId: 102092545
          tagName: oyasumi-vDEV
          releaseDraft: false
          prerelease: true
          includeDebug: true
          includeRelease: false
          includeUpdaterJson: true
      - name: Update release data
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log("Deleting existing oyasumi-vDEV tag...");
            try {
              await github.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "tags/oyasumi-vDEV"
              })
              console.log("Deleted existing oyasumi-vDEV tag!");
            } catch (e) {
              console.log("The oyasumi-vDEV tag doesn't exist yet: " + e)
            }
            console.log("Recreating oyasumi-vDEV tag on current commit...");
            try {
              await github.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "refs/tags/oyasumi-vDEV",
                sha: context.sha
              })
              console.log("Recreated oyasumi-vDEV tag!");
            } catch (e) {
              console.log("Could not recreate oyasumi-vDEV tag: " + e)
            }
            console.log("Updating release data...");
            try {
              await github.request('PATCH /repos/Raphiiko/Oyasumi/releases/102092545', {
                tag_name: 'oyasumi-vDEV',
                name: 'Oyasumi Development Build',
                body: `${{ steps.changelog_reader.outputs.changes }}`,
                draft: false,
                prerelease: true
              })
              console.log("Updated release data!");
            } catch (e) {
              console.log("Could not update release data: " + e)
            }
      - name: Sleep for 5 seconds
        run: Start-Sleep -s 5
        shell: powershell
      - name: Publish release if needed
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log("Publishing release...");
            try {
              await github.request('PATCH /repos/Raphiiko/Oyasumi/releases/102092545', {
                draft: false
              })
              console.log("Published release!");
            } catch (e) {
              console.log("Could not publish release: " + e)
            }
      - name: Update the update manifest
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GH_TOKEN_GIST }}
          gist_id: 8af3d105fe9a59db304cca2cfea216c8
          file_path: latest.json
          gist_file_name: 'oyasumi_update_manifest_dev.json'
          gist_description: Oyasumi Update Manifest [Development Channel]
