name: 'Steam Release Build'
on:
  push:
    branches:
      - develop
      - master
      - main

jobs:
  build-steam-release:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Get Package Version
        id: get-package-version
        uses: stevenbenitez/get-package-version-action@v1
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Initialize the project
        run: npm run ci
      - name: Set flavour to STEAM
        run: npm run set-flavour STEAM
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src-shared-rust
            src-elevated-sidecar
            src-core
      - name: Install development Tauri CLI
        run: cargo install --git https://github.com/tauri-apps/tauri --branch 1.x tauri-cli
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          version: ${{ steps.get-package-version.outputs.version }}
          path: ./CHANGELOG.md
      - name: Build OyasumiVR
        run: cargo-tauri build -b none
      - name: Deploy to Steam
        env:
          STEAM_BUILD_USER: ${{ secrets.STEAM_BUILD_USER }}
          STEAM_CONFIG_VDF: ${{ secrets.STEAM_CONFIG_VDF }}
          STEAM_APP_ID: '2538150'
          APP_VERSION: v${{ steps.get-package-version.outputs.version }}
        shell: bash
        run: chmod +x ./scripts/steam/steam-deploy.sh && ./scripts/steam/steam-deploy.sh
