name: 'Release Build'
on:
  push:
    branches:
      - master

jobs:
  build-release:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Get Package Version
        id: get-package-version
        uses: stevenbenitez/get-package-version-action@v1
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          version: ${{ steps.get-package-version.outputs.version }}
          path: ./CHANGELOG.md
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true
      #      - name: install dependencies (ubuntu only)
      #        if: matrix.platform == 'ubuntu-20.04'
      #        run: |
      #          sudo apt-get update
      #          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: install app dependencies
        run: yarn
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: oyasumi-v${{ steps.get-package-version.outputs.version }}
          releaseName: Oyasumi v${{ steps.get-package-version.outputs.version }}
          releaseBody: ${{ steps.changelog_reader.outputs.changes }}
          releaseDraft: false
          prerelease: true
      - name: Create tag
        uses: actions/github-script@v5
        env:
          OYASUMI_VERSION: ${{ steps.get-package-version.outputs.version }}
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/oyasumi-v' + process.env.OYASUMI_VERSION,
              sha: context.sha
            })
