name: 'PR & Feature Check'
on:
  pull_request:
  push:
    branches:
      - feature/*

jobs:
  check-pr-or-feature:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install NodeJS dependencies
        run: npm install --force
      - name: Lint Angular project
        run: npm run lint
      - name: Set app version to DEV version
        run: npm run set-version DEV
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      #      - name: install dependencies (ubuntu only)
      #        if: matrix.platform == 'ubuntu-20.04'
      #        run: |
      #          sudo apt-get update
      #          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: Configure Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src-shared
            src-elevated-sidecar
            src-tauri
      - name: Check Rust code in shared module
        run: cd src-shared && cargo clippy --all-features --no-deps
      - name: Check Rust code in elevated sidecar module
        run: cd src-elevated-sidecar && cargo clippy --all-features --no-deps
      - name: Check Rust code in core module
        run: >
          mkdir -p dist/oyasumi/ # Create empty dist folder
          mkdir -p src-elevated-sidecar/target/release/ # Create empty target folder for sidecar executable
          touch src-elevated-sidecar/target/release/oyasumi-elevated-sidecar.exe  # Create dummy sidecar executable
          node scripts/move-sidecar-build.js # Rename dummy sidecar executable to the correct name
          cd src-tauri
          cargo clippy --all-features --no-deps # Check Rust code in core module
          rm src-elevated-sidecar/target/release/oyasumi-elevated-sidecar*.exe # Clean up dummy sidecar executable(s)
      - name: Test if Oyasumi compiles
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

